### ISSUE TITLE
Il y a 2 blocs de textes identiques

### ISSUE THREAD

**Issue by Shagshag** [friends-of-presta/ecommerce-solidaire-minisite#5]
> La communauté Friends-of-Presta constituée d’experts PrestaShop se mobilise pour offrir aux TPE impactées par le confinement lié au COVID-19 un site de vente en ligne, gratuitement.
> 
> Commerçants, créateurs, artisans qui ont fermé l’accueil au public peuvent ainsi continuer à servir leur clientèle et proposer leurs produits en livraison ou en retrait.
> L'objectif est de gérer au mieux les stocks et notamment les denrées périssables. 

Le 1er et second blocs de texte du site sont les mêmes

**Comment by jf-viguier** [comment]
merci, c'est réglé
